# Generated by Django 4.0.4 on 2022-06-06 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySolarApp', '0004_profile_banner_pic_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField()),
                ('location', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('pic', models.ImageField(blank=True, upload_to='product_images')),
                ('short_desc', models.CharField(max_length=150, verbose_name='Short Description')),
                ('long_desc', models.CharField(max_length=5000, verbose_name='Long Description')),
                ('category', models.CharField(choices=[('SLP', 'Solar Panels'), ('BAT', 'Batteries'), ('INV', 'Inverters'), ('CHA_CTRL', 'Charge Controllers'), ('WAT_PUMPS', 'Water Pumps'), ('ACC', 'Accessories'), ('TOOLS', 'Tools'), ('MISC', 'Miscellaneous/Other')], default='MISC', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('in_stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='contact_info',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='banner_pic',
            field=models.ImageField(blank=True, upload_to='profile_and_banner_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_and_banner_images'),
        ),
        migrations.DeleteModel(
            name='store_item',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mySolarApp.profile'),
        ),
        migrations.AddField(
            model_name='delivery_info',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery_info',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySolarApp.product'),
        ),
    ]
