# Generated by Django 4.0.4 on 2022-06-08 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySolarApp', '0005_delivery_info_product_user_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_info',
            name='amount_of_item',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='delivery_info',
            name='payment_method',
            field=models.CharField(choices=[('On point', 'On point'), ('Online', 'Online')], default='On point', max_length=10),
        ),
        migrations.AlterField(
            model_name='delivery_info',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_deliveryInfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delivery_info',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_deliveryInfo', to='mySolarApp.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_seller', to='mySolarApp.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shopkeeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
