# Generated by Django 4.0.4 on 2022-06-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySolarApp', '0008_user_is_shopkeeper'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_info',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
