# Generated by Django 4.0.4 on 2022-06-13 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySolarApp', '0009_delivery_info_processed_product_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_info',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_deliveryInfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delivery_info',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_deliveryInfo', to='mySolarApp.product'),
        ),
    ]
