# Generated by Django 4.0.4 on 2022-06-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySolarApp', '0010_alter_delivery_info_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_info',
            name='delivery_date',
            field=models.DateTimeField(verbose_name='Delivery Date'),
        ),
    ]
