# Generated by Django 4.0.5 on 2022-07-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySolarApp', '0012_profile_how_active_profile_identification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='desc',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='how_active',
            new_name='how_activeWillYouBePerWeek',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='identification',
            new_name='identificationNumber',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='nameOfCompany',
        ),
    ]
