# Generated by Django 4.0.5 on 2022-07-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySolarApp', '0015_sellerrequests_alter_delivery_info_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sellerRequests',
        ),
    ]
