# Generated by Django 4.0.5 on 2022-07-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySolarApp', '0017_sellerrequests'),
    ]

    operations = [
        migrations.CreateModel(
            name='help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000, unique=True)),
                ('is_FAQ', models.BooleanField(default=False)),
            ],
        ),
    ]
