# Generated by Django 4.0.5 on 2022-07-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySolarApp', '0018_help'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='help',
            new_name='questions',
        ),
    ]
