# Generated by Django 4.0.5 on 2022-07-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySolarApp', '0020_rename_questions_userquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestions',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
