# Generated by Django 4.0.5 on 2022-07-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySolarApp', '0021_userquestions_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='beSellerFormSubmitted',
            field=models.BooleanField(default=False),
        ),
    ]
