# Generated by Django 4.0.5 on 2022-07-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySolarApp', '0022_user_besellerformsubmitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerrequests',
            name='how_active',
        ),
    ]
