# Generated by Django 4.0.5 on 2022-07-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySolarApp', '0023_remove_sellerrequests_how_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_info',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
