# Generated by Django 4.0.5 on 2022-07-26 13:34

from django.conf import settings
from django.db import migrations, models
import mySolarApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mySolarApp', '0025_delivery_info_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_info',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='delivery_info',
            name='customer',
            field=models.ForeignKey(on_delete=models.SET(mySolarApp.models.delivery_info.close_delivery), related_name='customer_deliveryInfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delivery_info',
            name='item',
            field=models.ForeignKey(on_delete=models.SET(mySolarApp.models.delivery_info.close_delivery), related_name='product_deliveryInfo', to='mySolarApp.product'),
        ),
        migrations.AlterField(
            model_name='delivery_info',
            name='seller',
            field=models.ForeignKey(on_delete=models.SET(mySolarApp.models.delivery_info.close_delivery), related_name='seller_deliveryInfo', to='mySolarApp.profile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=models.SET(mySolarApp.models.Product.close_product), related_name='product_seller', to='mySolarApp.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shopkeeper',
            field=models.ForeignKey(on_delete=models.SET(mySolarApp.models.Profile.deactivate_shopkeeper), to=settings.AUTH_USER_MODEL),
        ),
    ]
