# Generated by Django 4.0.5 on 2022-08-01 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySolarApp', '0026_delivery_info_closed_profile_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shopkeeper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sellerrequests',
            name='sellerAcc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
