# Generated by Django 4.0.5 on 2022-08-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySolarApp', '0027_alter_profile_shopkeeper_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
    ]
