# Generated by Django 4.0.5 on 2022-08-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySolarApp', '0028_remove_product_is_closed_remove_profile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='banner_pic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='sellerrequests',
            name='banner_pic',
        ),
        migrations.RemoveField(
            model_name='sellerrequests',
            name='profile_pic',
        ),
    ]
