# Generated by Django 4.0.5 on 2022-08-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySolarApp', '0029_remove_profile_banner_pic_remove_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_info',
            name='payment_method',
            field=models.CharField(choices=[('On point', 'On point')], default='On point', max_length=10),
        ),
    ]
