# Generated by Django 4.0.5 on 2022-08-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySolarApp', '0032_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='businessEmail',
            field=models.EmailField(default='None', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='businessNumber',
            field=models.CharField(default='None', max_length=13),
            preserve_default=False,
        ),
    ]
