# Generated by Django 4.0.5 on 2022-08-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySolarApp', '0033_profile_businessemail_profile_businessnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerrequests',
            name='how_active',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
