# Generated by Django 4.0.5 on 2022-08-17 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySolarApp', '0034_sellerrequests_how_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_info',
        ),
    ]
